# Start with a rustup image providing the stable release.
image: ${CI_REGISTRY}/kaios/sidl:1.49.0_3

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
stages:
    - build
    - tests
build:breakpad:
    stage: build
    script:
    - cargo build
test:cargo:
    stage: tests
    script: 
    - rustc --version && cargo --version
    - cargo test -- --nocapture